[workspace]
members = ["json_parser"]

[package]
name = "json_parser_rust"
version = "0.1.0"
edition = "2021"

[build]
target = "x86_64-pc-windows-msvc"

[dependencies]
json_parser = { path = "./json_parser" }

[lib]
crate-type = ["cdylib"]
